#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

wmake -j $targetType couplingModels
wmake -j $targetType biomassCombustion
wmake -j $targetType coalChemistryTurbulenceModels
wmake -j $targetType ./

#------------------------------------------------------------------------------
